
import './ui/global.css'

import CartPage from './homePage/page'
import  AllProducts from './categorypage/page'
import Categories from './homePage/page'
import SlideCategories from './Slidecarrosel/page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">

        <body>
          {children}
         </body>
      </html>
    )
  }